package plugin

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"testing"
)

// Only the selected false token may change. The arbitrary generated bytes are
// materialized as a TOML comment. Native Codex preserves ordinary/dotted tables;
// it rewrites inline containers, which the separate rejection property covers.
func FuzzCodexConfigPreservesBytes(f *testing.F) {
	f.Add([]byte("comment with false and true"), uint8(0))
	f.Add([]byte("\x00\n\xff"), uint8(1))
	f.Add([]byte("Unicode 日本語"), uint8(2))
	f.Add([]byte{}, uint8(3))
	f.Fuzz(func(t *testing.T, comment []byte, shape uint8) {
		// Bound materialization cost, not the generator's byte domain.
		if len(comment) > 1024*1024 {
			comment = comment[:1024*1024]
		}
		prefix := "# " + base64.StdEncoding.EncodeToString(comment) + "\n"
		forms := []string{
			"[plugins.\"demo@team\"]\nenabled = %s # keep this\n",
			"plugins.\"demo@team\".enabled = %s # keep this\n",
		}
		form := forms[int(shape)%len(forms)]
		original := []byte(prefix + fmt.Sprintf(form, "false"))
		want := []byte(prefix + fmt.Sprintf(form, "true"))
		got, err := codexEnabledConfig(original, "demo@team")
		if err != nil || !bytes.Equal(got, want) {
			t.Fatalf("selected enabled token was not the only change: %q %v", got, err)
		}
	})
}

func FuzzCodexConfigRejectsInline(f *testing.F) {
	f.Add([]byte("comment"), false, false)
	f.Add([]byte("\xff\x00"), true, true)
	f.Fuzz(func(t *testing.T, comment []byte, nested, enabled bool) {
		if len(comment) > 1024*1024 {
			comment = comment[:1024*1024]
		}
		prefix := "# " + base64.StdEncoding.EncodeToString(comment) + "\n"
		form := "plugins.\"demo@team\" = { enabled = %t, note = 'keep' }\n"
		if nested {
			form = "plugins = { \"demo@team\" = { enabled = %t }, \"other@team\" = { enabled = false } }\n"
		}
		if result, err := codexEnabledConfig([]byte(prefix+fmt.Sprintf(form, enabled)), "demo@team"); err == nil || result != nil {
			t.Fatalf("native inline rewrite was authorized: %q %v", result, err)
		}
	})
}

func TestCodexConfigRejectsUnknownEnabled(t *testing.T) {
	for _, data := range []string{"", "# enabled = false\n", "[plugins.\"other@team\"]\nenabled = false\n", "[plugins.\"demo@team\"]\nenabled = 'false'\n", "[plugins.\"demo@team\"]\nenabled = false\nenabled = true\n"} {
		if _, err := codexEnabledConfig([]byte(data), "demo@team"); err == nil {
			t.Fatalf("unknown/invalid enabled state accepted: %q", data)
		}
	}
}

func TestCodexConfigPreservesTrailingArrayTable(t *testing.T) {
	for _, enabled := range []bool{false, true} {
		original := fmt.Sprintf("[plugins.\"demo@team\"]\nenabled = false\n\n[[flags]]\nenabled = %t # unrelated\n", enabled)
		want := fmt.Sprintf("[plugins.\"demo@team\"]\nenabled = true\n\n[[flags]]\nenabled = %t # unrelated\n", enabled)
		got, err := codexEnabledConfig([]byte(original), "demo@team")
		if err != nil || string(got) != want {
			t.Fatalf("array table stole selected enabled token: %q %v", got, err)
		}
	}
}
