version: 2

project_name: skillshare

before:
  hooks:
    - go mod tidy
    - test -f internal/server/dist/index.html
    - 'test -n "$(find internal/server/dist/assets -maxdepth 1 -type f | head -n 1)"'

builds:
  - main: ./cmd/skillshare
    binary: skillshare
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: runkids
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/runkids/skillshare
    description: Share skills across AI CLI tools
    license: MIT
    install: |
      bin.install "skillshare"
    test: |
      system "#{bin}/skillshare", "version"
