package main

func printPluginHelp() {
	printHelp("skillshare plugin [command] [options]", "",
		helpGroup{title: "Commands", rows: []helpRow{
			{"list", "Browse managed plugins (default; TUI in a terminal)"},
			{"add [source]", "Choose a plugin from a directory or HTTPS Git repository,\nor add npm:<package> to Pi"},
			{"discover <source>", "Inspect source candidates without installing"},
			{"import [native-id]", "Adopt an existing native install with --from"},
			{"inspect <name>", "Show bindings and native installation state"},
			{"sync [name]", "Install missing bindings or retry pending operations"},
			{"check [name]", "Check source content for changes (read-only)"},
			{"update [name]", "Review and update supported targets"},
			{"enable [name]", "Select managed targets for the next sync"},
			{"disable [name]", "Deselect managed targets; the next sync removes their installs"},
			{"remove [name]", "Uninstall managed bindings; retain shared marketplaces"},
		}},
		helpGroup{title: "Options", rows: []helpRow{
			{"--target <target>", "Receiving client (repeat to select several; add without\nit keeps the plugin in Skillshare only)"},
			{"--plugin <name>", "Select one plugin from a marketplace"},
			{"--name <name>", "Logical Skillshare package name"},
			{"--from <target>", "Import from this native client in the selected scope"},
			{"-n, --dry-run", "Preview without writing config or Agent state"},
			{"--source-ref <ref>", "Git branch, tag or commit (discover/add/update)"},
			{"--entry <path>", "Explicit OpenCode JS/TS entry (discover/add)"},
			{"--revision <id>", "Require the matching preview before applying"},
			{"--json", "Machine-readable output, no interactive prompts"},
			{"--no-tui", "Plain output, no interactive prompts"},
			{"-g, --global", "Global configuration (native user scope)"},
			{"-p, --project", "Project configuration (supported targets only)"},
		}},
		helpGroup{title: "Targets", rows: []helpRow{
			{"Supported", "claude, codex, cursor, antigravity (desktop; alias: agy),\nantigravity-cli, copilot, grok, pi, opencode, omp"},
			{"Discovery only", "kimi, hermes, devin (native automation not yet verified)"},
			{"Project", "claude, antigravity, pi, opencode, omp"},
		}},
		helpNotes("Notes",
			"Sync alias: skillshare sync plugins [name] [--dry-run] [--json]",
			"Plugins are not included in sync --all. Complete plugin trees stay together.",
			"Grok requires native trust: install there first, then import.",
			"Cursor/Antigravity sync whole local folders; OpenCode syncs registrations.",
			"Pi project operations require native project trust.",
			"npm:<package> (as on pi.dev) is installed by Pi, which runs its install scripts.",
			"Codex has no project installation; update re-adds a plugin enabled in Codex.",
			"OMP manages marketplace plugins only and loads their extension modules at its next start.",
			"Enable/disable saves sync selection only; run sync to install/remove the target.",
			"Authentication, hook trust and command-source approval remain in the native client.",
			"Use check before update. Import does not reinstall or change enabled state.",
		),
	)
}
